export const globalCss = `
  @import url('https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&family=Plus+Jakarta+Sans:wght@400;500;600&display=swap');
  * { box-sizing: border-box; }
  body { margin: 0; font-family: 'Plus Jakarta Sans', system-ui, sans-serif; }
  input, button, select, textarea { font-family: inherit; color: inherit; }
  button { cursor: pointer; }
  button:disabled { opacity: 0.4; cursor: not-allowed; }
  input:focus, select:focus, textarea:focus { outline: 2px solid #7a6c5d; outline-offset: -1px; border-color: transparent; }
  ::-webkit-scrollbar { width: 8px; height: 8px; }
  ::-webkit-scrollbar-track { background: transparent; }
  ::-webkit-scrollbar-thumb { background: #d9cfc1; border-radius: 4px; }
`;

export const styles = {
  app: { minHeight: '100vh', background: '#FAF6EF', color: '#3a342c', paddingBottom: 80 },
  errorBar: { background: '#fbeae5', color: '#8b3a2c', padding: '10px 16px', textAlign: 'center', fontSize: 13, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, borderBottom: '1px solid #f0d4cb' },
  header: { position: 'sticky', top: 0, zIndex: 50, background: 'rgba(250, 246, 239, 0.92)', backdropFilter: 'blur(12px)', borderBottom: '1px solid rgba(122, 108, 93, 0.12)' },
  headerInner: { maxWidth: 1200, margin: '0 auto', padding: '14px 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 24, flexWrap: 'wrap' },
  brand: { display: 'flex', alignItems: 'center', gap: 12 },
  brandMark: { width: 36, height: 36, borderRadius: 18, background: '#3a342c', color: '#FAF6EF', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 22, fontFamily: 'Fraunces, serif', fontWeight: 500 },
  brandTitle: { fontFamily: 'Fraunces, serif', fontSize: 22, fontWeight: 500, letterSpacing: '-0.01em', lineHeight: 1 },
  brandSubtitle: { fontSize: 11, color: '#9b8c7a', marginTop: 3, letterSpacing: '0.04em' },
  nav: { display: 'flex', gap: 2, alignItems: 'center' },
  navBtn: { display: 'flex', alignItems: 'center', gap: 6, padding: '8px 12px', background: 'transparent', border: 'none', borderRadius: 8, color: '#7a6c5d', fontSize: 13, fontWeight: 500, transition: 'all 0.15s' },
  navBtnActive: { background: '#3a342c', color: '#FAF6EF' },
  badge: { background: '#c8a04c', color: '#3a342c', fontSize: 10, fontWeight: 600, padding: '1px 6px', borderRadius: 8, minWidth: 16, textAlign: 'center' },
  main: { maxWidth: 1100, margin: '0 auto', padding: '32px 24px' },
  pageHead: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 16, flexWrap: 'wrap', marginBottom: 24 },
  eyebrow: { fontSize: 11, color: '#9b8c7a', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 6 },
  h1: { fontFamily: 'Fraunces, serif', fontSize: 36, fontWeight: 500, letterSpacing: '-0.02em', margin: 0, lineHeight: 1.1 },
  weekStat: { textAlign: 'right' },
  weekStatNum: { fontFamily: 'Fraunces, serif', fontSize: 40, fontWeight: 500, color: '#3a342c', lineHeight: 1 },
  weekStatLabel: { fontSize: 11, color: '#9b8c7a', letterSpacing: '0.08em', textTransform: 'uppercase', marginTop: 4 },
  toolbar: { display: 'flex', gap: 8, marginBottom: 16, flexWrap: 'wrap' },
  searchBox: { display: 'flex', alignItems: 'center', gap: 8, padding: '0 12px', background: '#fff', border: '1px solid #e8dfd1', borderRadius: 10, flex: 1, minWidth: 200, height: 38 },
  searchInput: { border: 'none', background: 'transparent', flex: 1, fontSize: 14, padding: '8px 0', outline: 'none' },
  iconBtn: { display: 'flex', alignItems: 'center', justifyContent: 'center', width: 28, height: 28, borderRadius: 6, background: 'transparent', border: 'none', color: '#9b8c7a' },
  toolBtn: { display: 'flex', alignItems: 'center', gap: 6, height: 38, padding: '0 14px', background: '#fff', border: '1px solid #e8dfd1', borderRadius: 10, color: '#5a4530', fontSize: 13, fontWeight: 500, transition: 'all 0.15s' },
  toolBtnActive: { background: '#3a342c', color: '#FAF6EF', borderColor: '#3a342c' },
  toolBtnPrimary: { display: 'flex', alignItems: 'center', gap: 6, height: 38, padding: '0 16px', background: '#3a342c', color: '#FAF6EF', border: 'none', borderRadius: 10, fontSize: 13, fontWeight: 500 },
  filterPanel: { background: '#fff', border: '1px solid #e8dfd1', borderRadius: 12, padding: 16, marginBottom: 16 },
  filterRow: { marginBottom: 12 },
  filterLabel: { fontSize: 11, color: '#9b8c7a', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 8, fontWeight: 500 },
  chipRow: { display: 'flex', gap: 6, flexWrap: 'wrap' },
  chip: { padding: '6px 12px', background: '#FAF6EF', border: '1px solid #e8dfd1', borderRadius: 999, fontSize: 12, color: '#5a4530', fontWeight: 500 },
  chipActive: { background: '#3a342c', color: '#FAF6EF', borderColor: '#3a342c' },
  chipClear: { padding: '6px 12px', background: 'transparent', border: 'none', fontSize: 12, color: '#a85a4d', fontWeight: 500, textDecoration: 'underline', textUnderlineOffset: 3 },
  grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: 12 },
  card: { background: '#fff', border: '1.5px solid #e8dfd1', borderRadius: 14, overflow: 'hidden', position: 'relative', transition: 'border-color 0.15s, box-shadow 0.15s' },
  cardSelected: { borderColor: '#3a342c', boxShadow: '0 0 0 3px rgba(58, 52, 44, 0.08)' },
  cardMain: { width: '100%', border: 'none', background: 'transparent', padding: '14px 16px 12px', textAlign: 'left', display: 'block' },
  cardTop: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 },
  cardCat: { fontSize: 10, color: '#9b8c7a', letterSpacing: '0.1em', textTransform: 'uppercase', fontWeight: 600 },
  checkBox: { width: 22, height: 22, borderRadius: 6, border: '1.5px solid #c4b8a8', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#FAF6EF', transition: 'all 0.15s', flexShrink: 0, background: '#fff' },
  checkBoxOn: { background: '#3a342c', borderColor: '#3a342c' },
  cardName: { fontFamily: 'Fraunces, serif', fontSize: 18, fontWeight: 500, letterSpacing: '-0.01em', color: '#3a342c', marginBottom: 8, lineHeight: 1.25 },
  cardTags: { display: 'flex', gap: 5, flexWrap: 'wrap', marginBottom: 12 },
  cardTag: { fontSize: 11, padding: '2px 8px', background: '#FAF6EF', color: '#7a6c5d', borderRadius: 999, fontWeight: 500 },
  cardFoot: { display: 'flex', gap: 12, fontSize: 12, paddingTop: 10, borderTop: '1px solid #f0eadf' },
  cardStatItem: { color: '#7a6c5d', fontWeight: 500 },
  cardStatWarn: { color: '#a85a4d' },
  cardEditBtn: { position: 'absolute', top: 10, right: 36, width: 24, height: 24, background: 'transparent', border: 'none', color: '#c4b8a8', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: 6, opacity: 0.6 },
  stickyBar: { position: 'fixed', bottom: 16, left: 16, right: 16, maxWidth: 600, margin: '0 auto', background: '#3a342c', color: '#FAF6EF', padding: '14px 18px', borderRadius: 14, display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, boxShadow: '0 8px 24px rgba(58, 52, 44, 0.18)', zIndex: 40 },
  stickyText: { fontSize: 14, fontWeight: 600 },
  stickySub: { fontSize: 11, opacity: 0.65, marginTop: 2 },
  stickyBtn: { display: 'flex', alignItems: 'center', gap: 4, background: '#c8a04c', color: '#3a342c', border: 'none', padding: '10px 16px', borderRadius: 10, fontSize: 13, fontWeight: 600 },
  list: { display: 'flex', flexDirection: 'column', gap: 6 },
  listItem: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%', padding: '14px 16px', background: '#fff', border: '1px solid #e8dfd1', borderRadius: 10, textAlign: 'left', color: '#3a342c' },
  listItemName: { fontSize: 15, fontWeight: 500, fontFamily: 'Fraunces, serif' },
  listItemMeta: { fontSize: 12, color: '#7a6c5d', marginTop: 3 },
  shopWrap: { display: 'flex', flexDirection: 'column', gap: 14 },
  shopSection: { background: '#fff', border: '1px solid #e8dfd1', borderRadius: 12, overflow: 'hidden' },
  shopHead: { display: 'flex', alignItems: 'center', gap: 8, padding: '12px 16px', fontSize: 12, fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase', background: '#FAF6EF', borderBottom: '1px solid #f0eadf' },
  catDot: { width: 8, height: 8, borderRadius: 4, display: 'inline-block' },
  shopCount: { marginLeft: 'auto', fontSize: 11, color: '#9b8c7a', fontWeight: 500, textTransform: 'none', letterSpacing: 0 },
  shopRow: { display: 'flex', alignItems: 'center', gap: 12, padding: '12px 16px', borderBottom: '1px solid #f5f0e8', background: '#fff', border: 'none', borderTop: 'none', width: '100%', textAlign: 'left' },
  shopRowDone: { opacity: 0.4 },
  shopName: { fontSize: 14, fontWeight: 500 },
  shopMeta: { fontSize: 12, color: '#7a6c5d', marginTop: 2 },
  shopRecipe: { color: '#9b8c7a' },
  combinedTag: { color: '#5a7a4d', fontWeight: 500 },
  krogerBtn: { width: 30, height: 30, background: '#FAF6EF', border: '1px solid #e8dfd1', borderRadius: 8, color: '#5a4530', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  stapleHint: { fontSize: 12, color: '#9b8c7a', padding: '8px 16px', borderBottom: '1px solid #f5f0e8' },
  stapleRow: { opacity: 0.7 },
  stapleRowOn: { opacity: 1, background: '#fefaf0' },
  shopFooter: { marginTop: 24, display: 'flex', justifyContent: 'center' },
  plannedBanner: { display: 'flex', alignItems: 'center', gap: 8, padding: '12px 16px', background: '#fefaf0', border: '1px solid #f0e0b8', borderRadius: 10, fontSize: 13, color: '#7a5a2d', marginBottom: 16 },
  logForm: { background: '#fff', border: '1px solid #e8dfd1', borderRadius: 12, padding: 16, marginBottom: 16 },
  starRow: { display: 'flex', gap: 4 },
  starBtn: { background: 'transparent', border: 'none', padding: 4 },
  select: { width: '100%', padding: '10px 12px', border: '1px solid #e8dfd1', borderRadius: 8, background: '#fff', fontSize: 14, color: '#3a342c' },
  wrapGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: 10, marginBottom: 24 },
  bigStat: { background: '#fff', border: '1px solid #e8dfd1', borderRadius: 14, padding: '20px 18px', position: 'relative', overflow: 'hidden' },
  bigStatBar: { position: 'absolute', top: 0, left: 0, right: 0, height: 3 },
  bigStatValue: { fontFamily: 'Fraunces, serif', fontSize: 36, fontWeight: 500, color: '#3a342c', letterSpacing: '-0.02em', lineHeight: 1 },
  bigStatLabel: { fontSize: 11, color: '#9b8c7a', marginTop: 6, letterSpacing: '0.08em', textTransform: 'uppercase' },
  section: { background: '#fff', border: '1px solid #e8dfd1', borderRadius: 14, padding: 20, marginBottom: 16 },
  sectionTitle: { fontFamily: 'Fraunces, serif', fontSize: 18, fontWeight: 500, color: '#3a342c', marginBottom: 14, letterSpacing: '-0.01em' },
  sectionBody: {},
  twoCol: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 16, marginBottom: 16 },
  podium: { listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 10 },
  podiumRow: { display: 'flex', alignItems: 'center', gap: 14, padding: '12px 4px', borderBottom: '1px solid #f5f0e8' },
  podiumRank: { fontFamily: 'Fraunces, serif', fontSize: 26, fontWeight: 500, color: '#c4b8a8', width: 32, fontVariantNumeric: 'tabular-nums' },
  podiumName: { fontFamily: 'Fraunces, serif', fontSize: 17, fontWeight: 500, color: '#3a342c' },
  podiumMeta: { fontSize: 12, color: '#7a6c5d', marginTop: 2 },
  podiumCount: { fontFamily: 'Fraunces, serif', fontSize: 24, fontWeight: 500, color: '#3a342c' },
  podiumX: { fontSize: 14, color: '#9b8c7a', marginLeft: 2 },
  byCatRow: { display: 'grid', gridTemplateColumns: '90px 1fr auto', gap: 12, alignItems: 'center', padding: '10px 4px', borderBottom: '1px solid #f5f0e8' },
  byCatCat: { fontSize: 11, color: '#9b8c7a', textTransform: 'uppercase', letterSpacing: '0.06em', fontWeight: 600 },
  byCatName: { fontSize: 14, color: '#3a342c', fontWeight: 500 },
  byCatCount: { fontSize: 13, color: '#7a6c5d', fontWeight: 600 },
  notableRow: { padding: '10px 4px', borderBottom: '1px solid #f5f0e8' },
  notableLabel: { fontSize: 11, color: '#9b8c7a', textTransform: 'uppercase', letterSpacing: '0.06em', fontWeight: 600, marginBottom: 4 },
  notableValue: { fontFamily: 'Fraunces, serif', fontSize: 16, fontWeight: 500, color: '#3a342c' },
  notableSub: { fontSize: 12, color: '#7a6c5d', marginTop: 2 },
  monthChart: { display: 'grid', gridTemplateColumns: 'repeat(12, 1fr)', gap: 6, height: 160, alignItems: 'stretch' },
  monthCol: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'flex-end', gap: 4 },
  monthBarWrap: { width: '100%', flex: 1, display: 'flex', alignItems: 'flex-end' },
  monthBar: { width: '100%', background: 'linear-gradient(180deg, #c8a04c 0%, #a87f3a 100%)', borderRadius: 4, minHeight: 4 },
  monthCount: { fontSize: 11, color: '#7a6c5d', fontWeight: 600 },
  monthLabel: { fontSize: 10, color: '#9b8c7a', letterSpacing: '0.04em' },
  tagWrap: { display: 'flex', flexWrap: 'wrap', gap: 8, alignItems: 'center' },
  tagBig: { display: 'inline-flex', alignItems: 'center', gap: 5, padding: '6px 12px', background: '#FAF6EF', border: '1px solid #e8dfd1', borderRadius: 999, color: '#3a342c', fontWeight: 500 },
  ingRow: { display: 'flex', justifyContent: 'space-between', padding: '8px 4px', borderBottom: '1px solid #f5f0e8', fontSize: 14 },
  ingCount: { color: '#7a6c5d', fontWeight: 600, fontVariantNumeric: 'tabular-nums' },
  empty: { padding: 32, textAlign: 'center', background: '#fff', border: '1px dashed #e8dfd1', borderRadius: 12 },
  emptyState: { padding: '64px 24px', textAlign: 'center' },
  modalBg: { position: 'fixed', inset: 0, background: 'rgba(58, 52, 44, 0.4)', backdropFilter: 'blur(4px)', zIndex: 100, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 16 },
  modal: { background: '#FAF6EF', width: '100%', maxWidth: 560, maxHeight: '90vh', borderRadius: 18, overflow: 'hidden', display: 'flex', flexDirection: 'column', boxShadow: '0 20px 50px rgba(58, 52, 44, 0.2)' },
  modalHead: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '18px 20px', borderBottom: '1px solid #e8dfd1' },
  modalTitle: { fontFamily: 'Fraunces, serif', fontSize: 22, fontWeight: 500, margin: 0, letterSpacing: '-0.01em' },
  modalBody: { padding: 20, overflowY: 'auto', flex: 1 },
  modalFoot: { display: 'flex', gap: 8, padding: 16, borderTop: '1px solid #e8dfd1', background: '#fff' },
  input: { width: '100%', padding: '10px 12px', border: '1px solid #e8dfd1', borderRadius: 8, background: '#fff', fontSize: 14, color: '#3a342c' },
  textarea: { width: '100%', padding: '10px 12px', border: '1px solid #e8dfd1', borderRadius: 8, background: '#fff', fontSize: 14, color: '#3a342c', resize: 'vertical', fontFamily: 'inherit' },
  tagPill: { display: 'inline-flex', alignItems: 'center', gap: 4, padding: '4px 4px 4px 10px', background: '#3a342c', color: '#FAF6EF', borderRadius: 999, fontSize: 12, fontWeight: 500 },
  tagPillX: { background: 'rgba(250, 246, 239, 0.15)', border: 'none', color: '#FAF6EF', width: 18, height: 18, borderRadius: 9, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  divider: { height: 1, background: '#e8dfd1', margin: '20px 0 16px' },
  ingEditRow: { display: 'flex', alignItems: 'center', padding: '10px 12px', background: '#fff', border: '1px solid #e8dfd1', borderRadius: 8, marginBottom: 6 },
  ingAddCard: { background: '#fff', border: '1px dashed #c4b8a8', borderRadius: 10, padding: 12, marginTop: 8 },
  checkLine: { display: 'flex', alignItems: 'center', gap: 5, fontSize: 12, color: '#5a4530' },
  deleteBtn: { display: 'flex', alignItems: 'center', gap: 6, height: 38, padding: '0 14px', background: 'transparent', border: '1px solid #e8c5c0', borderRadius: 10, color: '#a85a4d', fontSize: 13, fontWeight: 500 },
  toast: { position: 'fixed', bottom: 24, left: '50%', transform: 'translateX(-50%)', background: '#3a342c', color: '#FAF6EF', padding: '12px 20px', borderRadius: 999, fontSize: 13, fontWeight: 500, boxShadow: '0 8px 20px rgba(58, 52, 44, 0.25)', zIndex: 200 },
};
